# `try`

```Python
try:
    num1 = int(input('나눠질 수: '))
    num2 = int(input('나누는 수: '))
    print('{0}/{1}={2}'.format(num1, num2, int(num1/num2)))
except ValueError:
    print('잘못된 값입니다')
# 나눠질 수: asdf
# 잘못된 값입니다
```

```Python
try:
    nums = []
    nums.append(int(input('나눠질 수: ')))
    nums.append(int(input('나누는 수: ')))
    # nums.append(int(nums[0]/nums[1]))
    print('{0}/{1}={2}'.format(nums[0], nums[1], nums[2]))
except ValueError:
    print('잘못된 값입니다')
except ZeroDivisionError as err:
    print(err)
    # 나눠질 수: 1
    # 나누는 수: 0
    # division by zero
```

```Python
try:
    nums = []
    nums.append(int(input('나눠질 수: ')))
    nums.append(int(input('나누는 수: ')))
    # nums.append(int(nums[0]/nums[1]))
    print('{0}/{1}={2}'.format(nums[0], nums[1], nums[2]))
except ValueError:
    print('잘못된 값입니다')
except ZeroDivisionError as err:
    print(err)
except Exception as err:
    print(err)
    # 나눠질 수: 4
    # 나누는 수: 2
    # list index out of range
```

[[오류 발생시키기]]